Card create js
paulotelles/todo_app pull request #4
Opened 2021-02-17 16:03 UTC by paulotelles

Ainda faltam os filtros e também limitar a quantidade de cards.

2021-02-17 22:51 UTC, vncsrbro requested changes

2021-02-17 22:51 UTC, vncsrbro commented on src/js/pages/index.js
> +mybutton.addEventListener("click", (event) => {
Aqui ta faltando verificar se os campos foram preenchidos para evitar de criar uma task vazia.

<img width="532" alt="Captura de Tela 2021-02-17 às 19 48 57" src="https://user-images.githubusercontent.com/30932300/108278051-30d18e80-7159-11eb-9baf-ae513907b0e6.png">

2021-02-17 22:51 UTC, vncsrbro commented on src/sass/components/_card.scss
>  .card.finalized {
Só pra relembrar o que tinha te dito antes: conseguimos usar no CSS um seletor de atributos, dessa forma você não precisa ficar manipulando as classes (add/remove). Ex:

`.classe[nome-do-atributo="Valor"]`
`.card[data-status="Finalized"]`

2021-02-18 16:53 UTC, paulotelles commented on src/js/pages/index.js
> +mybutton.addEventListener("click", (event) => {
corrigido, troquei o button do form por input type=submit, dessa maneira agora o submit só acontece caso tenha sido preenchido o conteudo do texto e da data.

2021-02-18 16:53 UTC, paulotelles commented on src/sass/components/_card.scss
>  .card.finalized {
fiz as alterações para utilizar desta maneira

2021-02-18 17:41 UTC, vncsrbro approved these changes
A estruturação da sua lógica está muito boa! Parabéns 🎉

2021-02-18 17:44 UTC, merged