Deletetask and filters
paulotelles/todo_app pull request #5
Opened 2021-02-18 21:00 UTC by paulotelles

Nesta atividade estão inclusos: botão de deletar e filtros.

2021-02-19 13:19 UTC, vncsrbro requested changes
No arquivo createTask.js a variável `let taskStorage = localStorage` é definida porém não é utilizada.

Por conta do limite na função generateKey quando adicionamos uma tarefa que ultrapassa o limite a aplicação trava. Se o limite é 10 só estou conseguindo adicionar 9 tarefas.

2021-02-19 13:19 UTC, vncsrbro commented on src/js/modules/buttonDelete.js
> +  console.log("entrei no button finalize");
Podemos remover o console.log do código final.

2021-02-19 13:19 UTC, vncsrbro commented on src/js/modules/searchFilter.js
> +  console.log(`Entraou toma a string: ${string}`);
Podemos remover o console.log do código final.

2021-02-19 13:19 UTC, vncsrbro commented on src/js/modules/searchFilter.js
> +  console.log(radioFilter);
Podemos remover o console.log do código final.

2021-02-19 13:19 UTC, vncsrbro commented on src/js/modules/searchFilter.js
> +      console.log(card.querySelector(".card-text").innerHTML);
Podemos remover o console.log do código final.

2021-02-19 13:19 UTC, vncsrbro commented on src/js/pages/index.js
> +  console.log(searchField.value);
Podemos remover o console.log do código final.

2021-02-19 13:19 UTC, vncsrbro commented on src/js/modules/searchFilter.js
> +function searchFilter(string) {
Nesse método seria bacana criar um retorno para o usuário caso a pesquisa não retorne nenhum resultado. Uma frase "Nenhuma tarefa foi encontrada".

2021-02-19 13:19 UTC, vncsrbro commented on src/js/pages/index.js
Os módulos createCard, dateConvert, finalizeTask e buttonFinalize estão sendo importados no index.js mas não estão sendo utilizados aqui.

2021-02-19 19:55 UTC, paulotelles commented on src/js/modules/buttonDelete.js
> +  console.log("entrei no button finalize");
corrigido

2021-02-19 19:55 UTC, paulotelles commented on src/js/modules/searchFilter.js
> +  console.log(`Entraou toma a string: ${string}`);
corrigido

2021-02-19 19:55 UTC, paulotelles commented on src/js/modules/searchFilter.js
> +  console.log(radioFilter);
corrigido

2021-02-19 19:55 UTC, paulotelles commented on src/js/modules/searchFilter.js
> +      console.log(card.querySelector(".card-text").innerHTML);
corrigido

2021-02-19 19:55 UTC, paulotelles commented on src/js/pages/index.js
> +  console.log(searchField.value);
corrigido

2021-02-19 19:56 UTC, paulotelles commented on src/js/modules/searchFilter.js
> +function searchFilter(string) {
feito

2021-02-19 19:56 UTC, paulotelles commented on src/js/pages/index.js
corrigido

2021-02-20 17:07 UTC, vncsrbro approved these changes

2021-02-20 20:13 UTC, merged